# Generated by Django 3.2.5 on 2021-07-16 15:05

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('patient', '0003_alter_patient_admission_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='patient',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patient_email',
        ),
        migrations.AddField(
            model_name='patient',
            name='date_joined',
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='someone@example.com',
                                    max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(
                blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                                         related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_active',
            field=models.BooleanField(
                default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_staff',
            field=models.BooleanField(
                default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_superuser',
            field=models.BooleanField(
                default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_login',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(
                blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(default='patient1', max_length=32),
        ),
        migrations.AddField(
            model_name='patient',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set',
                                         related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
