# Generated by Django 3.2.5 on 2021-07-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20210716_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='password',
            field=models.CharField(default='patient1', max_length=200),
        ),
    ]
