# Generated by Django 3.2.5 on 2021-07-29 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_doctor_profilepic'),
        ('patient', '0008_patient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='concerned_doctor',
            field=models.ForeignKey(
                default=3, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor'),
        ),
    ]
