# Generated by Django 3.2.5 on 2021-07-29 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_doctor_profilepic'),
        ('patient', '0009_patient_concerned_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='concerned_doctor',
            field=models.ForeignKey(default=3, help_text='Assign the Doctor',
                                    on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor'),
        ),
    ]
