# Generated by Django 3.2.5 on 2021-08-03 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_alter_doctor_profilepic'),
        ('patient', '0010_alter_patient_concerned_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='concerned_doctor',
            field=models.ForeignKey(blank=True, default=3, help_text='Assign the Doctor', null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor'),
        ),
    ]
