# Generated by Django 3.2.5 on 2021-08-03 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_alter_patient_concerned_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='concerned_doctor',
        ),
    ]
