# Generated by Django 3.2.5 on 2021-08-03 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_doctor_specialisation'),
        ('patient', '0013_patient_concerned_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='concerned_doctor',
            field=models.ForeignKey(blank=True, help_text='Assign the Doctor', null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor'),
        ),
    ]
