# Generated by Django 3.2.5 on 2021-08-16 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporttype', models.CharField(choices=[('R', 'Radiology Report'), ('B', 'Blood Report'), ('CT', 'CT Scan')], default='B', max_length=2)),
                ('concerned_doctor', models.ForeignKey(blank=True, help_text='The Prescribing Doctor', on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('report', models.ForeignKey(blank=True, help_text='Select the relevant Patient', null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
