# Generated by Django 3.2.5 on 2021-08-16 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='concerned_doctor',
            field=models.ForeignKey(blank=True, help_text='The Prescribing Doctor', null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor'),
        ),
    ]
