# Generated by Django 3.2.5 on 2021-08-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('fullname', models.CharField(max_length=100)),
                ('profilepic', models.ImageField(blank=True, upload_to='media/')),
                ('specialisation', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
