# Generated by Django 3.2.5 on 2021-08-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
