# Generated by Django 3.2.5 on 2021-08-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_doctor_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialisation',
            field=models.CharField(blank=True, default='General', max_length=100),
        ),
    ]
