# Generated by Django 3.2.5 on 2021-08-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_alter_doctor_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='specialisation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
